server:
  port: 80
spring:
  application:
    name: cloud-order_service

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进eureka server 默认true
    fetch-registry: true #是否从eureka server 抓取已有的注册信息，默认true,单点无所谓，集群必须设置为true才能配置ribbon实现
    #defaultZone:http://localhost:7001/eureka
    service-url:
      # 单机配置 defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka    #集群配置

