server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.235.100:8088 #配置nacos地址

management:
  endpoints:
    web:
      exposure:
        include: "*"