server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wp-9203/springCloud-config.git
          search-paths:
            - springCloud-config #搜素目录
          skip-ssl-validation: true
          username: wp-9203
          password: Wp@920312

      label: master #读取分支
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
