server:
  port: 7002



eureka:
  instance:
    hostname: eureka7002.com #eureka服务端实例名
  #单机配置 hostname: localhost #eureka服务端的实例名
  client:
    register-with-eureka: false  #false表示不向服务中心注册自己
    fetch-registry: false  #false表示自己就是服务中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/  #集群配置
      #设置与Eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
     #单机配置 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


